### ISSUE TITLE
Support language code and scroll to anchor for Help buttons

### ISSUE THREAD

**Issue by steima** [variocube/app-ui#23]
Append the currently selected language to the path of the Wiki entry `/en` `/de`.

Support scrolling to anchor if the help is shown in `<iframe />`.

**Comment by NgrillSolutions** [comment]
adding 3 properties: helpPage ,helpAnchor, language

should use scrollintoview to jump to the anchor position in Iframe

**Comment by NgrillSolutions** [comment]
problem accessing elements in iframe because this is blocked by browsers out of security reasons: https://stackoverflow.com/a/25098153

It's only possible if we add an event listener for messages in the wiki directly which gets from the app ui the id to scroll to.
![image](https://github.com/variocube/app-ui/assets/146322325/1a9a14fb-9676-4fd6-9628-2ab13c2478c0)
